project_id = "psjzzdycssokajbrhtol"

[functions.analyze-resume]
verify_jwt = false

[functions.analyze-interview-response]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-invalidation-notification]
verify_jwt = false

[functions.send-admin-message]
verify_jwt = false

[functions.send-referral-notification]
verify_jwt = false

[functions.send-referral-sms]
verify_jwt = false

[functions.parse-job-description]
verify_jwt = false

[functions.send-job-alerts]
verify_jwt = false

[functions.get-learning-resources]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false

[functions.send-daily-digest]
verify_jwt = false

[functions.send-interview-notification]
verify_jwt = false

[functions.contact-candidate]
verify_jwt = false

[functions.execute-code]
verify_jwt = false
