// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const EXPECTED_PROJECT_REF = "psjzzdycssokajbrhtol";
const FALLBACK_SUPABASE_URL = "https://psjzzdycssokajbrhtol.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzanp6ZHljc3Nva2FqYnJodG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NDMyNjUsImV4cCI6MjA4NDQxOTI2NX0.RrSz95KxhgU3F-_gsBOzr5zhjs82aI7tEFCK7gkjCsk";
const ENV_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const ENV_SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL =
  ENV_SUPABASE_URL && ENV_SUPABASE_URL.includes(EXPECTED_PROJECT_REF)
    ? ENV_SUPABASE_URL
    : FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  ENV_SUPABASE_URL && ENV_SUPABASE_URL.includes(EXPECTED_PROJECT_REF) && ENV_SUPABASE_KEY
    ? ENV_SUPABASE_KEY
    : FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (ENV_SUPABASE_URL && !ENV_SUPABASE_URL.includes(EXPECTED_PROJECT_REF)) {
  // eslint-disable-next-line no-console
  console.warn(
    "Supabase env vars point to a different project. Falling back to the configured ProvenHire project."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});